### ISSUE TITLE
Placeholder for encrypting S3 in Snowplow S3 Loader

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3746] opened 2018-04-30 10:04 UTC
This ticket is here to remind us that EmrEtlRunner should be able to support encrypted data when operating in "Stream Enrich" mode.

**Comment by BenFradet** [comment] 2018-06-07 13:37
closing as duplicate of snowplow/snowplow-s3-loader#53

**Comment by BenFradet** [comment] 2018-06-07 13:38
didn't read the desc, reopening

**Comment by BenFradet** [comment] 2018-06-13 15:09
This doesn't result in any changes, closing

**Closed by BenFradet** 2018-06-13 15:09 UTC

**Comment by alexanderdean** [comment] 2018-06-13 15:13
De-scheduled
