### ISSUE TITLE
Prevent Bots/Robots/Crawlets from getting passed Scala Kinesis Enrich

### ISSUE THREAD

**Issue by xkidro** [snowplow/snowplow#2118] opened 2015-10-14 08:15 UTC
Is there a way to reject bots entirely from getting passed enrich ?

From what I saw currently it just classifies them as br_type: Robot , I exclude these when I do queries to get pageviews and other events but it seems that it doesn't detect all of them for example Apple Bot is viewed as a normal browser...

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Applebot/0.1;  http://www.apple.com/go/applebot) 

Is there a way to manually add bots to make enrich at least detect them? it would be better if it was possible to reject or send them to the bad kinesis stream, I guess it would be better to have them in there if people actually want to know what they do on their website, this could be based on the feature that classifies them as bots currently.

For me having bots in the stats seems pretty pointless since I need to exclude them, they shouldn't be there in the first place.

**Comment by alexanderdean** [comment] 2015-10-14 08:36
Hi @xkidro!

In terms of better bot detection - the people to speak to are the IAB/ABC, who maintain a list: http://www.iab.com/guidelines/iababc-international-spiders-bots-list/ It would be cool to have a Snowplow Enrichment which used the IAB/ABC bots and spiders list.

> For me having bots in the stats seems pretty pointless since I need to exclude them, they shouldn't be there in the first place.

Lots of users don't want the bots in their event stream, but of course some do - in fact some are using Snowplow *only* to detect bots.

> it would be better if it was possible to reject or send them to the bad kinesis stream

We have thought about adding filtering capabilities to Kinesis Enrich, but it a) makes the event stream harder to audit and b) breaks the Unix philosophy of small stream workers which do one thing well. Instead, we are planning on creating a dedicated forker/filterer for Kinesis, here: https://github.com/snowplow/kinesis-tee

**Comment by alexanderdean** [comment] 2017-01-23 13:03
Duplicate of #937, closing

**Closed by alexanderdean** 2017-01-23 13:03 UTC
