### ISSUE TITLE
Javascript Collector: Internet explorer bug

### ISSUE THREAD

**Issue by esquire900** [snowplow/snowplow#2714] opened 2016-06-13 08:48 UTC
The Javascript collectors version [2.6.0](http://d1fc8wv8zag5ca.cloudfront.net/2.6.0/sp.js) & [2.6.1](http://d1fc8wv8zag5ca.cloudfront.net/2.6.1/sp.js) contain bugs, causing the script to fail on all versions of IE, as IE does not support the function string.startsWith.

More info can be found on [mozilla js reference](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith), adding that polyfill in front of the snowplow javscript collector script solved the problem for me.

**Comment by alexanderdean** [comment] 2016-06-13 08:55
Assigning to @fblundun to review

**Comment by fblundun** [comment] 2016-06-13 08:57
Thanks for raising @esquire900, but I am closing as this is a duplicate of https://github.com/snowplow/snowplow-javascript-tracker/issues/493 (which will be fixed in the next release of the JS Tracker and is currently in test).

**Closed by fblundun** 2016-06-13 08:57 UTC

**Comment by esquire900** [comment] 2016-06-13 09:50
Thank you for your quick reply @fblundun & @alexanderdean.

Please note that this also affects lots of other browsers (mostly mobile), fixing this bug in our snowplow script seems to increase traffic with almost 40%.
