### ISSUE TITLE
Scala Stream Collector: can't parse all useragents?

### ISSUE THREAD

**Issue by simplesteph** [snowplow/snowplow#2970] opened 2016-11-30 06:37 UTC
Not sure where in the code it's coming from, but I sometimes get the following warning:

```
05:23:09.567 [scala-stream-collector-akka.actor.default-dispatcher-12] WARN  s.can.server.HttpServerConnection - Illegal request header: Illegal 'User-Agent' header: Invalid input '=', expected TokenChar, '/', OptWS, Comment, ProductVersionComment or EOI (line 1, pos 138):
Mozilla/5.0 (iPhone; CPU iPhone OS 6_0_1 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A523 Safari/8536.25 t=/eIf6uJm7bq+TQw7s39CJg==DMTVmSsvTYYvgFAgMkVQrp==
                                                                
```

**Comment by asabourin** [comment] 2016-12-11 01:29
Following up on that issue we're seeing lot of similar errors caused by the iOS/Android Facebook apps custom user agents: 

> 00:58:02.290 [scala-stream-collector-akka.actor.default-dispatcher-9] WARN  s.can.server.HttpServerConnection - Illegal request header: Illegal 'User-Agent' header: Invalid input '[', expected ' ', '\t', LWS, Comment or ProductVersionComment (line 1, pos 156):
> Mozilla/5.0 (Linux; Android 6.0.1; SM-G930F Build/MMB29K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.124 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/103.0.0.20.72;]
>                                                                                                                                                            ^

> 00:58:02.367 [scala-stream-collector-akka.actor.default-dispatcher-9] WARN  s.can.server.HttpServerConnection - Illegal request header: Illegal 'User-Agent' header: Invalid input '[', expected ' ', '\t', LWS, Comment or ProductVersionComment (line 1, pos 113):
> Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Mobile/14A456 [FBAN/FBIOS;FBAV/60.0.0.37.141;FBBV/34183777;FBRV/0;FBDV/iPhone8,1;FBMD/iPhone;FBSN/iPhone OS;FBSV/10.0.2;FBSS/2;FBCR/OPTUS;FBID/phone;FBLC/en_GB;FBOP/5]
>                                                                                                                 ^

> 00:58:02.842 [scala-stream-collector-akka.actor.default-dispatcher-5] WARN  s.can.server.HttpServerConnection - Illegal request header: Illegal 'User-Agent' header: Invalid input '[', expected ' ', '\t', LWS, Comment or ProductVersionComment (line 1, pos 101):
> Mozilla/5.0 (iPad; CPU OS 7_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Mobile/11D167 [FBAN/FBIOS;FBAV/62.0.0.43.141;FBBV/36454510;FBRV/0;FBDV/iPad2,5;FBMD/iPad;FBSN/iPhone OS;FBSV/7.1;FBSS/1;FBCR/;FBID/tablet;FBLC/en_GB;FBOP/5]

**Comment by christoph-buente** [comment] 2017-06-07 11:11
Hi @alexanderdean,

i commented on the spray github, as we see an increasing amount of requests being discarded by the collector, as the useragent does not seem to be valid. From my point if view, this is hurting snowplow, as it makes us lose a significant amount of requests. See here: https://github.com/spray/spray/issues/458#issuecomment-306763534

**Comment by alexanderdean** [comment] 2017-06-07 12:18
Hey @christoph-buente - I believe Spray is no longer supported, and has been superceded by Akka HTTP.

I suggest we do two things:

1. Upgrade to the latest version of Akka HTTP for the collector - we should do this anyway
2. Lobby the Akka HTTP team to see if they would consider tolerating non-RFC compliant useragents
3. Consider a fork of Akka HTTP if they reject the idea

Thoughts?

**Comment by christoph-buente** [comment] 2017-06-07 13:55
Haha, got a nice answer :) You are right, spray is not supported anymore for several years. https://github.com/spray/spray/issues/458#issuecomment-306798110

Going forward with akka http sounds good to me.

**Comment by alexanderdean** [comment] 2017-08-02 13:24
Hey @BenFradet - does R92 solve this? If so, we should move this ticket in...

**Comment by BenFradet** [comment] 2017-08-02 13:27
it's already in r92, the move to akka-http should solve it by itself since akka-http is more relaxed than spray as far as ua are concerned from looking at the code. I had an integration test planned for this.

**Comment by BenFradet** [comment] 2017-09-18 11:54
A bit of an update on this: due to the parsing rules having been relaxed in akka-http less user-agents produce warnings.

However, despite the log messages, they are all successfully processed by the collector and further downstream.

Closing, thanks :+1: .

**Closed by BenFradet** 2017-09-18 11:54 UTC
Labels: 2. Collectors, bug, data-loss
