### ISSUE TITLE
Scala Common Enrich: issue with user-agent-utils enrichment's dvce_type and dvce_ismobile fields

### ISSUE THREAD

**Issue by danrama** [snowplow/snowplow#756] opened 2014-05-21 12:41 UTC
I've noticed some problems with the reliability of dvce_type and dvce_ismobile fields.  The detection of "Mobile" in particular seems buggy, as I frequently see User Agent strings like

`Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_2 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Mobile/11A501`

And these values in Snowplow:
```
dvce_type = Computer
dvce_ismobile = <blank>
os_name = Mac OS
os_family = Mac OS
os_manufacturer = Apple Inc.
br_name = Apple Mail
br_family = Apple Mail
br_type = Email Client
br_renderengine = WEBKIT
```
I looked at the [ClientEnrichments.scala#extractClientAttributes](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fsnowplow%2Fsnowplow%2Fblob%2F0.9.2%2F3-enrich%2Fscala-common-enrich%2Fsrc%2Fmain%2Fscala%2Fcom.snowplowanalytics.snowplow.enrich%2Fcommon%2Fenrichments%2FClientEnrichments.scala%23L113&sa=D&sntz=1&usg=AFQjCNEwGGPe969liCUcgBrxoXfncpR31Q) method and it seems to be correctly using the [UserAgent.java](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2FHaraldWalker%2Fuser-agent-utils%2Fblob%2F1.11%2Fsrc%2Fmain%2Fjava%2Feu%2Fbitwalker%2Fuseragentutils%2FUserAgent.java&sa=D&sntz=1&usg=AFQjCNGKx4KS-OR2eEmz1dqjzwwpOcUaMw) class of the [user-agent-utils](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2FHaraldWalker%2Fuser-agent-utils&sa=D&sntz=1&usg=AFQjCNFAH0ieZotL_QmQmd1G4bfbBVBxrA) library (version 1.11).  I thought maybe there's a bug in user-agent-utils, but when I created a unit test for the above User Agent string it got correctly detected:
```
@Test
public void testSnowplow() {
  String s = "Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_2 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Mobile/11A501";
  UserAgent userAgent = UserAgent.parseUserAgentString(s);
  assertEquals(Browser.APPLE_WEB_KIT, userAgent.getBrowser());
  assertEquals(OperatingSystem.iOS7_IPHONE, userAgent.getOperatingSystem());
  assertEquals(DeviceType.MOBILE, userAgent.getOperatingSystem().getDeviceType());
}
```
The only thing I can think of right now is that somehow the static declarations of the enum types in [OperatingSystem.java](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2FHaraldWalker%2Fuser-agent-utils%2Fblob%2F1.11%2Fsrc%2Fmain%2Fjava%2Feu%2Fbitwalker%2Fuseragentutils%2FOperatingSystem.java%23L48&sa=D&sntz=1&usg=AFQjCNGYK9w5hHo7vyM5RkSnBnzbQTbYDQ) is not deterministic when this library is being added into the Snowplow's scala-common-enrich Scala project?  So the [MAC_OS](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2FHaraldWalker%2Fuser-agent-utils%2Fblob%2F1.11%2Fsrc%2Fmain%2Fjava%2Feu%2Fbitwalker%2Fuseragentutils%2FOperatingSystem.java%23L109&sa=D&sntz=1&usg=AFQjCNGEQM9hKDKv4_F2WtgiZKPi-wK5TA) type gets created before the [IOS](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2FHaraldWalker%2Fuser-agent-utils%2Fblob%2F1.11%2Fsrc%2Fmain%2Fjava%2Feu%2Fbitwalker%2Fuseragentutils%2FOperatingSystem.java%23L93&sa=D&sntz=1&usg=AFQjCNHgyOskpLZLlFkXrGiUohDPzzhxTw) type (even though it is declared later in the source code), which causes it to be added first to the list of comparisons attempted in [OperatingSystem#parseUserAgentString](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2FHaraldWalker%2Fuser-agent-utils%2Fblob%2F1.11%2Fsrc%2Fmain%2Fjava%2Feu%2Fbitwalker%2Fuseragentutils%2FOperatingSystem.java%23L330&sa=D&sntz=1&usg=AFQjCNEL9qm4cGmdpBWyI_iREmcFOx8zAg)--consequently the User Agent substring for hardware/platform `(iPhone; CPU iPhone OS 7_0_2 like Mac OS X)` will match `Mac OS` before it matches `iPhone OS 7`.

**Comment by fblundun** [comment] 2015-08-12 14:57
I have tried plugging the user agent string `Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_2 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Mobile/11A501` into the Hadoop Enrich integration test suite, and I can't reproduce the problem. The user-agent-utils library has gone through several releases since this ticket was opened so perhaps it was a problem with the library that has been since been resolved.

I'm going to close this ticket since I can't reproduce the bug. We can reopen if it turns out to still exist.

**Closed by fblundun** 2015-08-12 14:57 UTC
Labels: 3. ETL
