### ISSUE TITLE
How to skip shredding for some events in storage loader

### ISSUE THREAD

**Issue by kala725** [snowplow/snowplow#2517] opened 2016-03-10 10:28 UTC
I am tracking multiple events , just a simple question, how to skip shred for some of the entries, for which I don't want custom events table. 

Eg: `Planning1` is the event_name, fr which I have a table called com_bd_snowplow_planning1 but for `planing2`, I just want a entry in events table (I want to skip shreding to individual events table). If I do --skip shred with the command, It just skips for all the data. How Can I do it just for planning2 and allow process of shred for planning1  as usual.

**Comment by alexanderdean** [comment] 2016-03-10 10:30
Hey @kala725 - in the future please direct questions to the Snowplow forum - snowplow-user@googlegroups.com In this case, I can restructure your ticket into a feature request...

**Comment by alexanderdean** [comment] 2016-03-10 10:31
Actually it already exists - closing as a dupe of #928

**Closed by alexanderdean** 2016-03-10 10:31 UTC
