### ISSUE TITLE
Contract violation error in snowplow-storage-loader archive_enriched phase

### ISSUE THREAD

**Issue by snowindy** [snowplow/snowplow#2123] opened 2015-10-16 10:26 UTC
Hi all, I use Snowplow r71. When EMR job finishes I do loading to my Postgres DB with 
/opt/snowplow-r71/snowplow-storage-loader -c /opt/snowplow-r71/config.yml

It downloads enriched events, loads to PG, archives from 'out' to 'storage-archive' folder, does not delete local files that used for COPY to PG, and then fails with this exception

```
  moving files from s3://snow-plow/out/ to s3://snow-plow/storage-archive/
(t0)    MOVE snow-plow/out/run=2015-10-16-08-30-55/_SUCCESS -> snow-plow/storage-archive/run=2015-10-16-08-30-55/_SUCCESS
      +-> snow-plow/storage-archive/run=2015-10-16-08-30-55/_SUCCESS
      x snow-plow/out/run=2015-10-16-08-30-55/_SUCCESS
Unexpected error: Contract violation for argument 1 of 1:
    Expected: String,
    Actual: nil
    Value guarded in: Sluice::Storage::S3::Location::initialize
    With Contract: String => Sluice::Storage::S3::Location
    At: /opt/snowplow-r71/snowplow-storage-loader!/gems/sluice-0.2.2/lib/sluice/storage/s3/location.rb:35
/opt/snowplow-r71/snowplow-storage-loader!/gems/contracts-0.7/lib/contracts.rb:69:in `Contract'
org/jruby/RubyProc.java:271:in `call'
/opt/snowplow-r71/snowplow-storage-loader!/gems/contracts-0.7/lib/contracts.rb:147:in `failure_callback'
/opt/snowplow-r71/snowplow-storage-loader!/gems/contracts-0.7/lib/contracts/decorators.rb:164:in `common_method_added'
/opt/snowplow-r71/snowplow-storage-loader!/gems/contracts-0.7/lib/contracts/decorators.rb:159:in `common_method_added'
/opt/snowplow-r71/snowplow-storage-loader!/storage-loader/lib/snowplow-storage-loader/s3_tasks.rb:91:in `archive_files_of_type'
/opt/snowplow-r71/snowplow-storage-loader!/storage-loader/lib/snowplow-storage-loader/s3_tasks.rb:68:in `archive_files'
file:/opt/snowplow-r71/snowplow-storage-loader!/storage-loader/bin/snowplow-storage-loader:63:in `(root)'
org/jruby/RubyKernel.java:1091:in `load'
file:/opt/snowplow-r71/snowplow-storage-loader!/META-INF/main.rb:1:in `(root)'
org/jruby/RubyKernel.java:1072:in `require'
file:/opt/snowplow-r71/snowplow-storage-loader!/META-INF/main.rb:1:in `(root)'
/tmp/jruby6807977102067423148extract/jruby-stdlib-1.7.20.1.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `(root)'
: snowplow-storage-loader failed with status 1
```

But if I do processing with 2 separate command that mimic the whole process overall, it's okay:
```
/opt/snowplow-r71/snowplow-storage-loader -c $snowplow_home/config.yml -s archive_enriched
/opt/snowplow-r71/snowplow-storage-loader -c $snowplow_home/config.yml -s download,delete,load,shred,analyze
```

**Comment by alexanderdean** [comment] 2015-10-16 10:28
That's odd - thanks for raising. We don't use PG much so it's quite possible a regression has slipped in. Assigning to our new CLI release, please add more info when you have it.

**Comment by snowindy** [comment] 2015-10-16 10:29
My config looks like this:

```
aws:
  access_key_id: XXX
  secret_access_key: XXX
  s3:
    region: us-east-1
    buckets:
      assets: s3://snowplow-hosted-assets
      log: s3://my-snowplow-bucket/log
      raw:
        in:
        - s3://elasticbeanstalk-us-east-1-XXX/resources/environments/logs/publish/e-XXX
        processing: s3://my-snowplow-bucket/processing
        archive: s3://my-snowplow-bucket/archive
      enriched:
        good: s3://my-snowplow-bucket/out
        bad: s3://my-snowplow-bucket/bad
        errors: s3://my-snowplow-bucket/errors
        archive: s3://my-snowplow-bucket/storage-archive
      shredded:
        good: s3://my-snowplow-bucket/out
        bad: s3://my-snowplow-bucket/bad
        errors: s3://my-snowplow-bucket/errors
        archive:
      jsonpath_assets:
  emr:
    ami_version: 3.7.0
    region: us-east-1
    jobflow_role: EMR_EC2_DefaultRole
    service_role: EMR_DefaultRole
    placement: us-east-1b
    ec2_key_name: emr-keypair
    bootstrap: []
    software:
      lingual: '1.1'
    jobflow:
      master_instance_type: m1.medium
      core_instance_count: 2
      core_instance_type: m1.medium
      task_instance_count: 0
      task_instance_type: m1.medium
      task_instance_bid: 0.015
    bootstrap_failure_tries: 3
collectors:
  format: clj-tomcat
enrich:
  job_name: Snowplow ETL
  versions:
    hadoop_enrich: 1.1.0
    hadoop_shred: 0.5.0
  continue_on_unexpected_error: false
  output_compression: NONE
storage:
  download:
    folder: /var/storageloader
  targets:
  - name: My PostgreSQL database
    type: postgres
    host: localhost
    database: xxxxx
    port: 5432
    table: atomic.events
    username: postgres
    password: xxxx
    maxerror:
    comprows:
    ssl_mode: disable
monitoring:
  tags: {}
  logging:
    level: DEBUG
  snowplow:
```

**Comment by snowindy** [comment] 2015-10-16 10:58
I updated issue body bottom with result of 2 commands execution.

**Comment by alexanderdean** [comment] 2015-10-16 10:59
Thanks

**Comment by fblundun** [comment] 2015-11-05 17:00
Looks like this is caused by the StorageLoader expecting a non-nil value in the configuration for `aws.s3.buckets.shredded.archive`, even though Postgres won't need that bucket.

A workaround is to use the `--skip shred` option to prevent [this line](https://github.com/snowplow/snowplow/blob/1cdb33ff42f0fbc3314f6f0edd27209883f5c915/4-storage/storage-loader/lib/snowplow-storage-loader/s3_tasks.rb#L68) from executing.

**Comment by fblundun** [comment] 2016-01-07 10:26
Following the release of r73 in December, an archive bucket for shred is necessary even when not using Redshift. So failing if the bucket isn't provided is no longer a bug.

**Closed by fblundun** 2016-01-07 10:26 UTC
Labels: 4. Storage, bug
