### ISSUE TITLE
Scala Hadoop Shred: issues fetching schemas in AMI 3.8.0

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1834] opened 2015-06-30 14:28 UTC
See this thread: https://groups.google.com/forum/#!topic/snowplow-user/cV_7pd178o8

**Comment by fblundun** [comment] 2015-08-07 14:50
May get fixed by #1720

**Comment by fblundun** [comment] 2015-08-13 12:07
I've just successfully reproduced this using a Hadoop Shred version which uses Hadoop 2.4.1. I get the same errors that were reported in the thread:

```
{"line":"snowplowweb\tweb\t2015-08-13 11:43:40.352\t2015-06-09 10:36:45.000\t2015-06-09 10:36:48.975\tpage_view\t29deb5cc-b6c5-4126-bb7a-89223c1a2354\t\tcloudfront\tjs-2.4.3\tcloudfront\thadoop-1.0.0-common-0.14.0\t1893875.322272248\t37.157.33.178\t2622883426\t3865bf4f087cbad3\t156\t\t\t\t\t\t\t\t\t\t\t\t\thttp://snowplowanalytics.com/test\tPage not found <80><93> Snowplow\t\thttp\tsnowplowanalytics.com\t80\t/test\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\"schema\":\"iglu:com.snowplowanalytics.snowplow/contexts/jsonschema/1-0-0\",\"data\":[{\"schema\":\"iglu:org.schema/WebPage/jsonschema/1-0-0\",\"data\":{\"genre\":\"test\",\"inLanguage\":\"en-US\"}},{\"schema\":\"iglu:org.w3/PerformanceTiming/jsonschema/1-0-0\",\"data\":{\"navigationStart\":1433846208625,\"unloadEventStart\":1433846208714,\"unloadEventEnd\":1433846208714,\"redirectStart\":0,\"redirectEnd\":0,\"fetchStart\":1433846208626,\"domainLookupStart\":1433846208626,\"domainLookupEnd\":1433846208626,\"connectStart\":1433846208626,\"connectEnd\":1433846208626,\"secureConnectionStart\":0,\"requestStart\":1433846208627,\"responseStart\":1433846208711,\"responseEnd\":1433846208713,\"domLoading\":1433846208721,\"domInteractive\":1433846208894,\"domContentLoadedEventStart\":1433846208899,\"domContentLoadedEventEnd\":1433846208907,\"domComplete\":0,\"loadEventStart\":0,\"loadEventEnd\":0,\"chromeFirstPaint\":1433846208929}}]}\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tMozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36\t\t\t\t\t\ten-US\t1\t1\t1\t0\t0\t0\t0\t0\t0\t1\t24\t1680\t1341\t\t\t\tEurope/London\t\t\t2560\t1440\tUTF-8\t1680\t1341\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t","errors":[{"level":"error","message":"Could not find schema with key iglu:com.snowplowanalytics.snowplow/contexts/jsonschema/1-0-0 in any repository, tried:","repositories":["Iglu Client Embedded [embedded]","Iglu Central [HTTP]"]}]}
```

**Comment by fblundun** [comment] 2015-08-13 13:38
It seems to work fine in AMI 3.7.0.

**Comment by fblundun** [comment] 2015-08-13 14:06
There's some information on changes between AMI versions [here](http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/ami-versions-supported.html) but none of the changes for 3.8.0 seem very suspicious

**Comment by alexanderdean** [comment] 2015-08-13 14:17
@fblundun - given that 3.8.0 is problematic and 3.6.0 is deprecated, maybe in 71 we change the recommendation to 3.7.0?

After that, we'll leapfrog 3.8.0 and move to the 4.x series in due course.

**Comment by fblundun** [comment] 2015-08-13 14:38
I agree - closing since probably won't support 3.8.0.

**Closed by fblundun** 2015-08-13 14:38 UTC
Labels: 3. ETL

**Comment by fblundun** [comment] 2016-01-07 17:29
This is fixed by https://github.com/snowplow/iglu-scala-client/issues/42, just like #1926

**Comment by alexanderdean** [comment] 2016-01-07 17:30
Aha! Good to know...
