### ISSUE TITLE
Stream Enrich: investigate the WARNING Unknown keyword exclusiveMinimum

### ISSUE THREAD

**Issue by benjben** [snowplow/snowplow#4268] opened 2020-01-27 08:38 UTC
There is always this warning in Stream Enrich's logs:
```
     [main] WARN com.networknt.schema.JsonMetaSchema - Unknown keyword exclusiveMinimum - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
```

**Comment by chuwy** [comment] 2020-01-27 09:45
The problem is in Iglu Client. Likely will be fixed by https://github.com/snowplow/snowplow/issues/4265

**Comment by benjben** [comment] 2020-01-27 09:47
Awesome!

**Comment by benjben** [comment] 2020-04-15 07:41
Pushing back as #4265 is being pushed back as well

**Comment by chuwy** [comment] 2020-06-19 16:31
Migrated to https://github.com/snowplow/enrich/issues/53

**Closed** 2020-06-19 16:33 UTC
Labels: enrich
