### ISSUE TITLE
EmrEtlRunner: race condition overwriting files during staging step

### ISSUE THREAD

**Issue by vceron** [snowplow/snowplow#3085] opened 2017-01-30 17:09 UTC
Some raw files are misnamed during the [CloudFront-like conversion process](https://github.com/snowplow/snowplow/blob/master/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/s3_tasks.rb#L80), causing 2 root problems of missing files.

In the example below the time-stamp into the filename of both files is always renamed as 2017-01-13-03 (UTC). A 2017-01-13-04 file is missing.

EmrEtlRunner output:
```
[Fri Jan 13 06:15:05 UTC 2017] (t3)    MOVE snowplow-collectors-log/e-xrnips2p/i-050292a49/_var_log_tomcat8_rotated_localhost_access_log.txt1484280061.gz -> viadeo-snowplow-processing/processing/var_log_tomcat8_rotated_localhost_access_log.2017-01-13-03.us-east-1.i-050292a49944536d7.txt.gz
[Fri Jan 13 06:15:05 UTC 2017] (t5)    MOVE snowplow-collectors-log/e-xrnips2p/i-050292a49/_var_log_tomcat8_rotated_localhost_access_log.txt1484276462.gz -> viadeo-snowplow-processing/processing/var_log_tomcat8_rotated_localhost_access_log.2017-01-13-03.us-east-1.i-050292a49944536d7.txt.gz
```

Time-stamp conversion should be : 
- 1484280061 = 13/1/2017 at 5:01:01 CET
- 1484276462 = 13/1/2017 at 4:01:02 CET

So, when the file is archived the "2017-01-13-0**3**" could be either the one at 5:01 or the one at 4:01 without any file named as "2017-01-13-0**4**"

______ 
**Additional info :** 
- We have more than 30,000 files in our raw/in bucket ( remaining Elastic Beanstalk logs)
- I wasn't able to verify if the issue comes from ruby or jruby ([suspect bug](https://github.com/jruby/jruby/issues/3670) in jruby)
Maybe the [bump to 9.1.6.0 ](https://github.com/snowplow/snowplow/pull/3029/commits/70c9bc1dba4a9be01dcb086a9881a768deb527eb) could fix the issue but I wasn't able to make run the snowplow-emr-etl-runner & snowplow-storage-loader with this version.
- We have this issue at least once every two days

**Bonus :** 
Maybe keeping the timestamp in the filename could be interesting to validate the converted CloudFront format.

**Related**:
- [61 Pygmy Parrot](https://github.com/snowplow/snowplow/milestone/64?closed=1)
  - #1398 - EmrEtlRunner: change Clojure Collector log timestamp format to match CloudFront logs ( https://github.com/snowplow/snowplow/commit/4b36d14868340821b8665d326376383faf0f41ab) 
  - #1379 - EmrEtlRunner: append region name to Clojure Collector log files
  - #1404 - EmrEtlRunner: append rather than prepend instance names to Clojure Collector log files

**Comment by alexanderdean** [comment] 2017-01-30 23:08
Hi @vceron - thanks for the detailed bug report. If the problem is indeed https://github.com/jruby/jruby/issues/3670, then hopefully it will be fixed when we release R87 very soon. Can you re-test once this has been released?

**Comment by vceron** [comment] 2017-01-31 14:15
> The problem must be something to do with threads

Yes, now I truly believe it is linked to [threads usage in Sluice](https://github.com/snowplow/sluice/blob/master/lib/sluice/storage/s3/s3.rb#L410).

Now I've no problems with processing raw files but with the storage in archive.
This morning i identified 4 missing files for yesterday's runs (1h, 9h, 12h, 21h).

`grep -i "archive/raw" | grep MOVE | egrep "30-01|30-09|30-12|30-21"`
Doing the previous grep on EmrEtlRunner output I found that some files wrere overwritten, independently of the instance.

```
[Mon Jan 30 08:15:05 UTC 2017] (t5)    MOVE snowplow-processing/processing/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-01.us-east-1.i-096c6fe1.txt.gz -> snowplow-archive/raw/2017-01-30/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-01.us-east-1.i-096c6fe1.txt.gz
[Mon Jan 30 08:15:05 UTC 2017] (t7)    MOVE snowplow-processing/processing/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-01.us-east-1.i-d5bf5d5z.txt.gz -> snowplow-archive/raw/2017-01-30/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-01.us-east-1.i-050292a4.txt.gz
[Mon Jan 30 08:15:05 UTC 2017] (t0)    MOVE snowplow-processing/processing/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-01.us-east-1.i-050292a4.txt.gz -> snowplow-archive/raw/2017-01-30/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-01.us-east-1.i-050292a4.txt.gz

[Mon Jan 30 09:52:04 UTC 2017] (t8)    MOVE snowplow-processing/processing/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-09.us-east-1.i-d5bf5d5z.txt.gz -> snowplow-archive/raw/2017-01-30/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-09.us-east-1.i-d5bf5d5z.txt.gz
[Mon Jan 30 09:52:04 UTC 2017] (t5)    MOVE snowplow-processing/processing/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-09.us-east-1.i-050292a4.txt.gz -> snowplow-archive/raw/2017-01-30/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-09.us-east-1.i-096c6fe1.txt.gz
[Mon Jan 30 09:52:04 UTC 2017] (t6)    MOVE snowplow-processing/processing/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-09.us-east-1.i-096c6fe1.txt.gz -> snowplow-archive/raw/2017-01-30/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-09.us-east-1.i-096c6fe1.txt.gz

[Mon Jan 30 12:52:05 UTC 2017] (t6)    MOVE snowplow-processing/processing/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-12.us-east-1.i-d5bf5d5z.txt.gz -> snowplow-archive/raw/2017-01-30/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-12.us-east-1.i-d5bf5d5z.txt.gz
[Mon Jan 30 12:52:05 UTC 2017] (t4)    MOVE snowplow-processing/processing/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-12.us-east-1.i-050292a4.txt.gz -> snowplow-archive/raw/2017-01-30/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-12.us-east-1.i-050292a4.txt.gz
[Mon Jan 30 12:52:05 UTC 2017] (t5)    MOVE snowplow-processing/processing/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-12.us-east-1.i-096c6fe1.txt.gz -> snowplow-archive/raw/2017-01-30/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-12.us-east-1.i-d5bf5d5z.txt.gz

[Mon Jan 30 23:15:05 UTC 2017] (t4)    MOVE snowplow-processing/processing/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-21.us-east-1.i-050292a4.txt.gz -> snowplow-archive/raw/2017-01-30/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-21.us-east-1.i-096c6fe1.txt.gz
[Mon Jan 30 23:15:05 UTC 2017] (t5)    MOVE snowplow-processing/processing/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-21.us-east-1.i-096c6fe1.txt.gz -> snowplow-archive/raw/2017-01-30/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-21.us-east-1.i-096c6fe1.txt.gz
[Mon Jan 30 23:15:05 UTC 2017] (t6)    MOVE snowplow-processing/processing/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-21.us-east-1.i-d5bf5d5z.txt.gz -> snowplow-archive/raw/2017-01-30/var_log_tomcat8_rotated_localhost_access_log.2017-01-30-21.us-east-1.i-d5bf5d5z.txt.gz
```

I'm looking forward to install the [R87](https://git.io/vDLFX)

**Comment by BenFradet** [comment] 2017-05-30 14:39
@vceron Have you had a chance to update to emr etl runner 0.23 (or 0.24) as we updated jruby to 9.1.6 in both those releases?

**Comment by vceron** [comment] 2017-06-19 13:47
Not yet @BenFradet. We'll update the stack to the last version in some days (a couple of weeks).

**Comment by BenFradet** [comment] 2017-08-07 14:55
will be fixed by #3136

**Closed by BenFradet** 2017-08-07 14:55 UTC

**Comment by vceron** [comment] 2017-08-08 09:15
The  jruby update to 9.1.6 in [r87-chichen-itza](https://github.com/snowplow/snowplow/releases/r87-chichen-itza) helped into, or even fixed, this issue.

![image](https://user-images.githubusercontent.com/2420834/29064289-c82aa71e-7c28-11e7-9e5f-ce226d64ca4c.png)

From the graph : 
- before mid-July we had the r86 with the raw files copying issue.
- from mid-July until start of August the indicator was broken, as the pattern in S3 bucket changed (to run=xxxxx)
- from August the indicator was fixed and we notice all the raw files are OK. [Here](https://gist.github.com/vceron/014dd82cec201862dc8da1020cbd9a3f) you have a gist to monitor the raw files if needed

**Comment by BenFradet** [comment] 2017-08-08 10:06
@vceron we have experienced this bug post r87 too, that's why we're going forward with the fix in #276 and not 3136. my bad

**Comment by alexanderdean** [comment] 2017-08-08 11:03
Thanks for the additional detail @vceron . Glad the problem stopped for you from R87...

**Comment by vceron** [comment] 2017-08-08 11:24
So the changes will allow to stage everything (raw, enriched, shredded) from the EMR cluster as for the raw files @BenFradet ?
At least for the last 8 days it is OK @alexanderdean, ill keep monitoring it for some weeks before concluding it is solved.

**Comment by BenFradet** [comment] 2017-08-08 11:26
The changes discussed here will move the staging step away from Sluice to S3DistCp.

**Comment by alexanderdean** [comment] 2017-08-17 08:53
Why did you remove the labels @BenFradet ?

**Comment by BenFradet** [comment] 2017-08-17 08:56
Since it's been treated in another issue, it prevents people from going back to the e.g. data-loss label x months from now and look at what happened in this ticket.

**Comment by alexanderdean** [comment] 2017-08-17 08:57
I disagree - a bug report is immutable - it intrinsically relates to data loss, and that doesn't change with the fix in another ticket. Removing the work assignment metadata by contrast is fine.
