### ISSUE TITLE
Add :compression_format: to StorageLoader

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#677] opened 2014-04-23 10:33 UTC
Because if we are loading lzo into Redshift, we need to specify `LZOP` in the `COPY` command.

**Comment by alexanderdean** [comment] 2015-07-03 09:11
Is this a duplicate @fblundun ?

**Comment by fblundun** [comment] 2015-07-03 09:12
Yes, closing since this is a duplicate of #1265

**Closed by fblundun** 2015-07-03 09:12 UTC
Labels: 4. Storage
