### ISSUE TITLE
Add ability to collect SendGrid events in Snowplow

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#716] opened 2014-05-02 09:58 UTC
Placeholder ticket.

http://blog.programmableweb.com/2014/02/20/how-to-use-mixpanel-to-track-sendgrid-email-delivery/

**Comment by alexanderdean** [comment] 2015-04-22 16:30
The SendGrid events are pretty straightforward. If anyone is interested in picking this one up:

1. Read this guide to writing a Snowplow webhook adapter: https://github.com/snowplow/snowplow/wiki/How-to-integrate-a-webhook-into-Snowplow
2. Review the existing email webhook implementations: Mandrill and Mailchimp (google for "Snowplow Mandrill" and "Snowplow MailChimp")

**Comment by fblundun** [comment] 2015-11-06 16:16
Closing as duplicate of #1161

**Closed by fblundun** 2015-11-06 16:16 UTC
Labels: 2. Collectors, 3. ETL, 4. Storage, 5. Data modeling
