### ISSUE TITLE
Scala Stream Collector: explore HTTP2 support

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3015] opened 2016-12-24 00:04 UTC
Per https://aws.amazon.com/about-aws/whats-new/2016/08/aws-elastic-beanstalk-supports-application-load-balancer/

**Comment by ryanrozich** [comment] 2016-12-24 02:13
My first question would be whether the Clojure collector should just work out of the box with HTTP2 and whether there are any code changes required at all. 

See point #1 in Mark Nottinghams blog post below

https://www.mnot.net/blog/2014/01/30/http2_expectations

Quote:
> In fact, the library that you use for HTTP/1 can be updated to support HTTP/2 without changing any application code.

**Comment by BenFradet** [comment] 2017-08-07 14:57
duplicate of #3073

**Closed by BenFradet** 2017-08-07 14:57 UTC
