### ISSUE TITLE
Update wiki page for Specific-event-tracking-with-the-Javascript-tracker

### ISSUE THREAD

**Issue by christoph-buente** [snowplow/snowplow#2007] opened 2015-08-31 09:41 UTC
I updated the wiki page. It basically adds the information how to add a currency to transactions and transaction items. I know it was possible in js tracker 2.20 and later, so i changed only those pages.

As there seems to be no proper pull request mechanism for the wiki pages: please pull at your convenience from this commit.

https://github.com/christoph-buente/snowplow-wiki/commit/94eb75420b0bfc16198c9964c915c41ee0d23827

Best, Christoph

**Comment by alexanderdean** [comment] 2015-08-31 22:37
Thanks! Can you sign our CLA? https://github.com/snowplow/snowplow/wiki/CLA

**Comment by christoph-buente** [comment] 2015-09-03 13:27
Sure, done.

**Comment by alexanderdean** [comment] 2015-09-03 13:30
Confirmed - thanks so much!

**Comment by fblundun** [comment] 2015-09-03 13:55
Thanks @christoph-buente! Closing since this is now in the wiki's master branch.

**Closed by fblundun** 2015-09-03 13:55 UTC
Labels: documentation
