### ISSUE TITLE
Kinesis Elasticsearch Sink: investigate support for multiple Elasticsearch versions

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2601] opened 2016-04-15 09:24 UTC
This may involve having two versions of the same artifact. Maybe we would have to use something like Maven Shade, or even have two separate KES builds?

**Comment by BenFradet** [comment] 2017-07-03 14:07
~ duplicate of snowplow/snowplow-elasticsearch-loader#10

**Closed by BenFradet** 2017-07-03 14:07 UTC
