### ISSUE TITLE
StorageLoader: add support for loading JSONs into Postgres

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#657] opened 2014-04-18 10:38 UTC

**Comment by chuwy** [comment] 2017-08-17 11:13
Duplicate of https://github.com/snowplow/snowplow/issues/3204

**Closed by chuwy** 2017-08-17 11:13 UTC
Labels: 4. Storage

**Comment by ganeshsp** [comment] 2018-04-04 06:05
Hello Guys,

Can you please help me to load shredded-tyes into postgresql?
all events are getting enriched and shredded properly.
atomic.events are getting loaded properly . but other tables like link_click_1 are not loading.
Please help me out to resolve this

**Comment by chuwy** [comment] 2018-04-04 07:04
Hey @ganeshsp! Please direct support questions to [our forums](https://discourse.snowplowanalytics.com/).
