### ISSUE TITLE
AMP support for contexts

### ISSUE THREAD

**Issue by shermozle** [snowplow/snowplow#3191] opened 2017-04-12 05:41 UTC
AMP needs to support custom contexts alongside pageviews and structured events. Okay for the logic of formatting these to be pushed to the server-side rendering, which limits it solely to content and event metadata.

**Comment by mattleong** [comment] 2018-08-01 20:45
Any solution for this?

**Comment by BenFradet** [comment] 2019-02-20 10:23
dupe of #2998, closing

**Closed by BenFradet** 2019-02-20 10:23 UTC
