### ISSUE TITLE
Common: define JSON Schema & populate for R81 build process

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2705] opened 2016-06-07 10:19 UTC
I think it can be as simple as a collection of dependencies and a collection of artifacts, which will each have a version.

**Comment by alexanderdean** [comment] 2017-10-27 08:50
This is too complex for this release, and maybe should live in Release Manager.

**Comment by joehamm** [comment] 2018-03-23 03:06
This is what’s wrong here . There was an internet search performed because the one party Was instructed  not to knock or text  and simply walk into an address he had never been before. Suspicious  an internet search was performed  with what little information was axailavble , being a phone number a previously used phone number and the address given that day and an address given nearby on an earlier date. And nick name.The party felt it was likely that the other party had done some possible illegal activity and may have been wanted by police . He felt he was told to go somewhere so he could be observed  and by no mean would walk into some unknown residence without alerting the tenets. This was odd. The internet search results were odd as what the provided. This being strange caused the other to call search for arrest records for other party. The traffic all around the house was clear something wasn’t write.  There was an obvious surveillance of the area  which scared the affected party that they thought he was there for something seriously criminal. The party left the neighborhood but was harassed and followed immediately after that. He has been harassed every since. What was intended to be an internet search for his safety thanks to Baxter hacker led to horrendous stalking and massive privacy rapings.

**Comment by BenFradet** [comment] 2019-02-19 15:30
closing

**Closed by BenFradet** 2019-02-19 15:30 UTC
Labels: 0. Common
