### ISSUE TITLE
EmrEtlRunner: failure to run from archive_enriched & archive_shredded if enriched is empty

### ISSUE THREAD

**Issue by ihortom** [snowplow/snowplow#3551] opened 2017-12-19 20:18 UTC
When `enriched/good` folder is empty both run from `archive_enriched` and `archive_shredded` fail to run. Using `archive_shredded` still checks `enriched/good` and thus both are affected by the same condition.

**Comment by alexanderdean** [comment] 2017-12-19 21:00
Thanks for raising @ihortom - assigning to @BenFradet to investigate.

**Comment by chuwy** [comment] 2018-03-12 08:06
Actually it seems like a #3436 duplicate, which was fixed in R95. De-scheduling now, but @ihortom please let us know if you remember any details.

**Comment by alexanderdean** [comment] 2018-03-12 12:27
Don't de-schedule - keep it in until confirmed by @ihortom

**Comment by chuwy** [comment] 2018-03-22 12:42
Hey @ihortom, this issue is still missing implementation because I still believe it was #3436. Could you please confirm?

**Comment by chuwy** [comment] 2018-03-23 09:29
Great! I think it was fixed in R95. Closing.

**Closed by chuwy** 2018-03-23 09:29 UTC
Labels: bug
