### ISSUE TITLE
Scala Common Enrich: bump Akka Streams to 2.0.4

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2690] opened 2016-05-26 09:58 UTC
```
[info] Total for specification MapTransformerSpec
[info] Finished in 1 ms
[info] 2 examples, 0 failure, 0 error
localhost - - [26/May/2016 09:43:00] "GET /guest/api/lookup-test/snowplower?format=json HTTP/1.1" 200 -
localhost - - [26/May/2016 09:43:00] "POST /api/lookup+test/snowplower/j-ZKIY4CKQRX72/32.1?date=2014-11-10T08%3A38%3A30.000Z HTTP/1.1" 200 -
[ERROR] [05/26/2016 09:43:00.956] [api-request-system-akka.actor.default-dispatcher-5] [ActorSystem(api-request-system)] Outgoing request stream error
java.lang.IllegalArgumentException: requirement failed: Cannot pull closed port
    at scala.Predef$.require(Predef.scala:233)
    at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:419)
    at akka.http.impl.engine.client.OutgoingConnectionBlueprint$ResponseParsingMerge$$anon$3$$anonfun$1.apply$mcV$sp(OutgoingConnectionBlueprint.scala:207)
    at akka.stream.stage.GraphStageLogic$Emitting.followUp(GraphStage.scala:830)
    at akka.stream.stage.GraphStageLogic$EmittingSingle.onPull(GraphStage.scala:879)
    at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:593)
    at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:533)
    at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:445)
    at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:400)
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:549)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:495)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
    at akka.dispatch.Mailbox.run(Mailbox.scala:220)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
[info] ApiRequestEnrichmentIntegrationTest
[info] 
[info] This is a integration test for the ApiRequestEnrichment
[info] + Basic Case
[info] x POST, Auth, JSON inputs, cache, several outputs
[error]    'Failure(NonEmptyList(java.lang.IllegalArgumentException: requirement failed: Cannot pull closed portjava.lang.IllegalArgumentException: requirement failed: Cannot pull closed port))' is not Success (ApiRequestEnrichmentIntegrationTest.scala:289)
[info] 
[info] 
[info] Total for specification ApiRequestEnrichmentIntegrationTest
[info] Finished in 0 ms
[info] 2 examples, 1 failure, 0 error
```

In e.g. this Travis build: https://travis-ci.org/snowplow/snowplow/builds/133065328

**Comment by chuwy** [comment] 2016-05-26 10:12
Seems like [this](https://github.com/akka/akka/issues/19094) bug. But from what I can see in their history - it is fixed in 2.0.2 which is used in API Enrichment. I'll try to reproduce.

**Comment by chuwy** [comment] 2016-05-27 05:52
Looks like it has been really fixed in 2.0.3 http://akka.io/news/2016/01/26/akka-streams-2.0.3-released.html. Should we create separate ticket to bump?

**Comment by fblundun** [comment] 2016-05-27 08:40
I have renamed this ticket!

**Comment by chuwy** [comment] 2016-05-27 08:41
Thanks. But I guess, it will be better to bump straight to 2.0.4.

**Comment by fblundun** [comment] 2016-05-27 08:43
Good point.

**Comment by BenFradet** [comment] 2017-08-07 15:54
moved away from akka-streams, closing

**Closed by BenFradet** 2017-08-07 15:54 UTC
