### ISSUE TITLE
Scala Common Enrich: pass a copy of the enriched event to JS enrichment so that it can't modify the fields in-place

### ISSUE THREAD

**Issue by benjben** [snowplow/snowplow#4288] opened 2020-03-04 11:42 UTC
Currently JS enrichment can modify the fields of the enriched event in-place, with for instance
```
event.setPlatform("whatever")
```
in the JS function.

**Comment by chuwy** [comment] 2020-03-04 12:22
Duplicate of https://github.com/snowplow/snowplow/issues/3913

**Closed by chuwy** 2020-03-04 12:22 UTC
Labels: 3.1. SCE
