### ISSUE TITLE
Javascript enableFormTracking does not allow for blacklisting or whitelisting

### ISSUE THREAD

**Issue by digitaltouch** [snowplow/snowplow#1436] opened 2015-02-20 00:26 UTC
This becomes an issue if the form that is being tracked captures credit card information.

**Comment by alexanderdean** [comment] 2015-02-20 07:59
Duplicate of https://github.com/snowplow/snowplow-javascript-tracker/issues/287

**Closed by alexanderdean** 2015-02-20 07:59 UTC
