### ISSUE TITLE
Scala Hadoop Shred: bump common enrich to 0.15.0

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#1812] opened 2015-06-24 10:38 UTC

**Comment by alexanderdean** [comment] 2015-06-24 11:48
This can wait till R69

**Comment by jbeemster** [comment] 2015-06-24 11:50
I did it already, the commit is in the commit to bump common enrich to 0.15.0.  It is all updated.  I can revert that section if you want?

**Comment by alexanderdean** [comment] 2015-06-24 11:51
Yep please revert - let's keep this release Kinesis-only...

**Comment by jbeemster** [comment] 2015-06-24 11:52
No worries shall do.

**Comment by fblundun** [comment] 2015-08-07 14:52
Duplicate of #1935, closing...

**Closed by fblundun** 2015-08-07 14:52 UTC
Labels: 3. ETL
