### ISSUE TITLE
Scala Hadoop Shred: add ability to filter based on event type

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#928] opened 2014-07-28 08:05 UTC
The idea comes from #927 - basically, have a list of event types that you are interested in shredding, which is passed in as a configuration option.

The idea is that a company with 500 event types may only be interested in shredding a subset into dedicated Redshift tables.

**Comment by kala725** [comment] 2016-03-11 07:49
@alexanderdean : My basic question was that only, How to define that which event to shred, as a configuration option?

**Comment by alexanderdean** [comment] 2017-01-31 20:21
Or filter based on app_id - this is driven by the insight that a Snowplow user may have some apps with huge event volumes (e.g. in-game events, ad impressions) that they want to keep out of Redshift, but some apps with manageable event volumes (e.g. ecomm transactions, admin UI usage) that they want to analyze in Redshift.

Given these various use cases, it would probably be best to support arbitrary filtering logic (JavaScript based?).

**Comment by BenFradet** [comment] 2019-02-19 14:31
dupe of snowplow/snowplow-rdb-loader#59, closing

**Closed by BenFradet** 2019-02-19 14:31 UTC
Labels: 4. Storage
