### ISSUE TITLE
Kinesis Elasticsearch Sink: rename dvce_timestamp, add missing fields

### ISSUE THREAD

**Issue by jramos** [snowplow/snowplow#2141] opened 2015-10-23 17:18 UTC
I get warnings with the current version of the sink about a difference in the number of fields. I also noticed that `dvce_timestamp` was not renamed to `dvce_created_timestamp`. This commit corrects both:

https://github.com/jramos/snowplow/commit/8790fd3671db54ba0fbb5dd6cafacb790517fe4c

**Comment by alexanderdean** [comment] 2015-10-23 17:22
Duplicate of #2089

**Closed by alexanderdean** 2015-10-23 17:22 UTC
