### ISSUE TITLE
Gradle cannot find maven repo, unable to download Android Snowplow library

### ISSUE THREAD

**Issue by nasahapps** [snowplow/snowplow#2043] opened 2015-09-08 23:57 UTC
The Wiki says to put in your build.gradle file:  

`maven { url "http://maven.snplow.com/releases" }`  

But in doing so, Gradle hangs because it is unable to find this repo. And yes, I triple-checked to make sure "Offline work" is unchecked.  

Despite the fact that maven.snplow.com says "This repository is operational", it apparently isn't for Gradle.  

Running on Gradle 2.6, Android Studio 1.4 Beta 2.  

My suggestion? JCenter. Works fine for everyone else.

**Comment by alexanderdean** [comment] 2015-09-09 06:36
Duplicate of https://github.com/snowplow/snowplow-android-tracker/issues/167

**Closed by alexanderdean** 2015-09-09 06:36 UTC
