### ISSUE TITLE
Snowplow Lzo S3 Sink ignores AWS region setting for dynamodb table

### ISSUE THREAD

**Issue by kavehfa** [snowplow/snowplow#1587] opened 2015-04-08 04:48 UTC
Snowplow Lzo S3 Sink ignores AWS region setting for dynamodb table and creates the table in us-east-1

**Comment by fblundun** [comment] 2015-04-08 07:59
Hi @kavehfa ,

This will be fixed in the next release of the sink (which will be going into test soon).

Closing as duplicate of #1582

**Closed by fblundun** 2015-04-08 07:59 UTC
Labels: 4. Storage
